### ISSUE TITLE
Adjustments needed in the New Sync Page

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2489]
This issue follows the work done in #2448. Items that still need to be done:

- [x] assets/css/sync.css could make some usage of CSS vars (1 h) https://github.com/10up/ElasticPress/pull/2561
- [x] --offset parameter is not working as expected on EP.io #2591
- [x] Errors count is not correct yet. If an "Entity too large" request is fired, the count is still showing "0". Same for the count of errors line for individual posts errors #2590
- [x] Sync page should show the progress of WP-CLI sync (1.5 h) https://github.com/10up/ElasticPress/pull/2564
- [x] When an indexing is stopped by the WP-CLI command we should show a message on the output (https://github.com/10up/ElasticPress/pull/2549)
- [x] Fix the AJAX URL when the EP is activated in a subsite (that is not the main site) #2501
- [x] In includes/classes/IndexHelper.php, `$start_date_time->format( 'D, F d, Y H:i' )` should be internationalized, so it can be localized later (https://github.com/10up/ElasticPress/pull/2548)

**Comment by felipeelia** [comment]
Now that all items were addressed, this can be closed.
