### ISSUE TITLE
Facet by Meta Block

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#3291]
### Is your enhancement related to a problem? Please describe.

After the foundations of the new Facet by Meta block were merged in #3289, there is still some work to do, mainly related to the frontend side of things:

- [ ] Implement an actual range slider in the block renderer
- [ ] Improve notice in the preview saying the field might not be a numeric field (background, color, etc.)
- [ ] Improve UI for field selection (can be done after 4.5.0)

Until we have an improved UI for the field selection, this feature will be available only by adding this snippet (to be made available as a plugin during the 4.5.0 release):

```php
add_filter(
	'ep_facet_types',
	function ( $types ) {
		$types['meta-range'] = '\ElasticPress\Feature\Facets\Types\MetaRange\FacetType';
		return $types;
	}
);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
