### ISSUE TITLE
Update `apiVersion` of all blocks to version 3

### ISSUE THREAD

**Issue by fabiankaegy** [10up/ElasticPress#3912]
ElasticPress contains several blocks. These blocks currently all use `apiVerson: 2`. In order to not prevent adoption of the iFramed post editor these should get updated to `apiVersion: 3`.

> [Version 3 (>= WordPress 6.3)](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-api-versions/#version-3-wordpress-6-3)
> The post editor will be iframed if all registered blocks have a Block API version 3 or higher and the editor has no classic meta boxes below the blocks. Adding version 3 support means that the block should work inside an iframe, though the block may still be rendered outside the iframe if not all blocks support version 3.

```[tasklist]
### Tasks
- [ ] [`elasticpress/comments`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/comments/block.json#L4)
- [ ] [`elasticpress/facet-date`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/facets/date/block.json#L4)
- [ ] [`elasticpress/facet-post-type`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/facets/post-type/block.json#L4)
- [ ] [`elasticpress/facet`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/facets/taxonomy/block.json#L4)
- [ ] [`elasticpress/related-posts`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/related-posts/block.json#L4)
- [ ] [`elasticpress/facet-meta`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/facets/meta/block.json#L4)
- [ ] [`elasticpress/facet-meta-range`](https://github.com/10up/ElasticPress/blob/f0151d46e6ef60b5f0139a09cc594049c57e0f1e/assets/js/blocks/facets/meta-range/block.json#L4)
```

**Comment by felipeelia** [comment]
Thanks @fabiankaegy but we are already tracking progress for this in #3853.

**Comment by fabiankaegy** [comment]
🤦 I tried searching for it but didn't find it somehow. Sorry for the duplicate
